### ISSUE TITLE
Customize the appearance

### ISSUE THREAD

**Issue by mircea-pavel-anton** [mircea-pavel-anton/mirceanton.com#20]
I would like to change the theme to something a bit darker, maybe more similar to the VSCode color theme.

Additionally, I don't really like the way the navbar looks when scrolling, but unless there is a relatively quick fix, i am not willing to spend too too much time on that as it is nitpicky.

**Comment by mirceanton** [comment]
Too broad, has been split into multiple issues

**Comment by mircea-pavel-anton** [comment]
Too broad, has been split into multiple issues
